                                                                Suyash Tambe
                                                                22070126117
                                                                AIML B2

In [1]:
import numpy as  np 
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, pairwise_distances

In [52]:
df = pd.read_csv(r"C:\Users\Suyash Tambe\Desktop\Unspervised learning\Class Assignment\Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [62]:
column1 = df['SepalLengthCm']
column2 = df['SepalWidthCm']


column1_array = np.array(column1).reshape(-1, 1)
column2_array = np.array(column2).reshape(-1, 1)

In [63]:
euclidean_dist = euclidean_distances(column1_array, column2_array)

In [55]:
print("Euclidean distance between column1 and column2:", euclidean_dist[0][0])
# The Euclidean distance of 1.6 suggests that there is a moderate difference between the values in column1 and column2. This means that the values in these columns are not very similar but also not drastically different.

Euclidean distance between column1 and column2: 1.6000000000000008

In [56]:
manhattan_dist = manhattan_distances(column1_array, column2_array)

In [57]:
print("Manhattan distance between column1 and column2:", manhattan_dist[0][0])
# The Manhattan distance of approximately 1.6 is very close to the Euclidean distance of 1.6. This suggests that the difference between the values in column1 and column2 is consistent across all dimensions (features), without the influence of the squared terms as in the Euclidean distance.

Manhattan distance between column1 and column2: 1.5999999999999996

In [58]:
minkowski_dist = pairwise_distances(column1_array, column2_array, metric='minkowski', p=3)

In [59]:
print("Minkowski distance (p=3) between column1 and column2:", minkowski_dist[0][0])
#  The Minkowski distance withp=3 closely resembles the Manhattan distance, suggests that the discrepancy between the values in column1 and column2 remains consistent across all dimensions, mirroring the behavior observed with the Manhattan distance.

Minkowski distance (p=3) between column1 and column2: 1.5999999999999996

Q2

In [72]:
from sklearn.metrics import jaccard_score

In [64]:
df = pd.read_csv(r"C:\Users\Suyash Tambe\Desktop\Unspervised learning\Class Assignment\apple_quality.csv")
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [66]:
df.describe()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,1999.500000,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277
std,1154.844867,1.928059,1.602507,1.943441,1.402757,1.930286,1.874427
min,0.000000,-7.151703,-7.149848,-6.894485,-6.055058,-5.961897,-5.864599
25%,999.750000,-1.816765,-2.011770,-1.738425,0.062764,-0.801286,-0.771677
50%,1999.500000,-0.513703,-0.984736,-0.504758,0.998249,0.534219,0.503445
75%,2999.250000,0.805526,0.030976,0.801922,1.894234,1.835976,1.766212
max,3999.000000,6.406367,5.790714,6.374916,7.619852,7.364403,7.237837

In [67]:
df = df.dropna()

In [68]:
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3995,3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good

In [78]:
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality,Quality_Flag
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good,1
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good,1
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad,0
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good,1
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good,1
...,...,...,...,...,...,...,...,...,...,...
3995,3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad,0
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good,1
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad,0
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good,1
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good,1

In [96]:
column1 = df['Quality']
column2 = df['Crunchiness']

In [93]:
column1_binary = (column1 == column1.iloc[0]).astype(int)
column2_binary = (column2 == column2.iloc[0]).astype(int)
# the boolean results (good or bad) are converted to integers using .astype(int)

In [94]:
jaccard_distance = 1 - jaccard_score(column1_binary, column2_binary)

In [95]:
print(f"Jaccard Distance: {jaccard_distance}")
# The Jaccard Distance indicates a very high dissimilarity between the binary representations of column1 and column2.
# This suggests that the majority of values in one column do not match the corresponding values in the other column.

Jaccard Distance: 0.9995009980039921